# Generated by Django 5.2 on 2025-04-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_drink_food_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
