# Generated by Django 5.2 on 2025-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='NoNameEntered', max_length=150),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
