# Generated by Django 5.2 on 2025-04-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid')], default='CREATED', max_length=20),
        ),
    ]
