# Generated by Django 5.2 on 2025-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('VIACARD', 'ViaCard'), ('CREDITCARD', 'CreditCard'), ('MOBILEPAY', 'MobilePay'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
